repos:
  - repo: https://github.com/frnmst/md-toc
    rev: 9.0.0
    hooks:
      - id: md-toc
        args: ["--in-place", "--skip-lines", "20", "github", "--header-levels", "4", "README.md"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.3.7'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: test.*
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli
      args: [--ignore-words-list, astroid ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
        exclude: test.*
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        exclude: |
          (?x)^(
            test.*|
            mkdocs.yml
          )$
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: "^tests/resources/"
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: requirements-txt-fixer
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        additional_dependencies: ["gibberish-detector"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: ["pydantic>2.0", "toml", "types-all"]

ci:
  autofix_prs: false
