name: CI

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

defaults:
  run:
    shell: bash

env:
  PYTHONUTF8: "1"

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Check git is working
        run: |
          git config --global user.email "bumpsemver-test-git@github.actions"
          git config --global user.name "Testing Git"
          git --version
          git config --list
      - name: Install test dependencies
        run: poetry install
      - name: Test
        run: poetry run pytest --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: zhaow-de/bumpsemver
          files: test-reports/coverage.xml
          flags: python-${{ matrix.python-version }}
          verbose: false
          env_vars: OS,PYTHON
